version: "3"

# networks:
#     cluster_net:

services:
    database:
        image : neo4j:4.0
        ports:
            - 7474:7474
            - 6477:6477
            - 7687:7687
        volumes: 
            - ~/logs/:/logs/             
            - ~/data:/data
            - ~/plugins:/plugins
            - ~/conf:/conf
        environment: 
            - NEO4J_AUTH=${NEO4J_AUTH}
            # - NEO4J_dbms_connector_https_advertised__address=0.0.0.0
            # - NEO4J_dbms_connector_http_advertised__address=0.0.0.0
            # - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0
            # - NEO4J_dbms_connector_http_listen__address=:7474
            # - NEO4J_dbms_connector_https_listen__address=:6477
            # - NEO4J_dbms_connector_bolt_listen__address=:7687
            - NEO4J_dbms_allow__upgrade=true
            - NEO4JLABS_PLUGINS=["apoc"]
        restart: unless-stopped

